// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pdf_open_mupdf
SEXP pdf_open_mupdf(std::string path);
RcppExport SEXP _rmupdf_pdf_open_mupdf(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(pdf_open_mupdf(path));
    return rcpp_result_gen;
END_RCPP
}
// pdf_close_mupdf
void pdf_close_mupdf(SEXP doc_xptr);
RcppExport SEXP _rmupdf_pdf_close_mupdf(SEXP doc_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_xptr(doc_xptrSEXP);
    pdf_close_mupdf(doc_xptr);
    return R_NilValue;
END_RCPP
}
// pdf_pages_mupdf
int pdf_pages_mupdf(SEXP doc_xptr);
RcppExport SEXP _rmupdf_pdf_pages_mupdf(SEXP doc_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_xptr(doc_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(pdf_pages_mupdf(doc_xptr));
    return rcpp_result_gen;
END_RCPP
}
// pdf_get_metadata_mupdf
Rcpp::List pdf_get_metadata_mupdf(SEXP doc_xptr);
RcppExport SEXP _rmupdf_pdf_get_metadata_mupdf(SEXP doc_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_xptr(doc_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(pdf_get_metadata_mupdf(doc_xptr));
    return rcpp_result_gen;
END_RCPP
}
// pdf_set_metadata_mupdf
void pdf_set_metadata_mupdf(SEXP doc_xptr, Rcpp::Nullable<std::string> title, Rcpp::Nullable<std::string> author, Rcpp::Nullable<std::string> subject, Rcpp::Nullable<std::string> keywords, Rcpp::Nullable<std::string> creator, Rcpp::Nullable<std::string> producer);
RcppExport SEXP _rmupdf_pdf_set_metadata_mupdf(SEXP doc_xptrSEXP, SEXP titleSEXP, SEXP authorSEXP, SEXP subjectSEXP, SEXP keywordsSEXP, SEXP creatorSEXP, SEXP producerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_xptr(doc_xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type title(titleSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type author(authorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type keywords(keywordsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type creator(creatorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type producer(producerSEXP);
    pdf_set_metadata_mupdf(doc_xptr, title, author, subject, keywords, creator, producer);
    return R_NilValue;
END_RCPP
}
// pdf_list_annots_mupdf
Rcpp::DataFrame pdf_list_annots_mupdf(SEXP doc_xptr, int page);
RcppExport SEXP _rmupdf_pdf_list_annots_mupdf(SEXP doc_xptrSEXP, SEXP pageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_xptr(doc_xptrSEXP);
    Rcpp::traits::input_parameter< int >::type page(pageSEXP);
    rcpp_result_gen = Rcpp::wrap(pdf_list_annots_mupdf(doc_xptr, page));
    return rcpp_result_gen;
END_RCPP
}
// pdf_add_highlight_mupdf
void pdf_add_highlight_mupdf(SEXP doc_xptr, int page, double x, double y, double width, double height, Rcpp::Nullable<std::string> contents, double r, double g, double b, bool fallback_square);
RcppExport SEXP _rmupdf_pdf_add_highlight_mupdf(SEXP doc_xptrSEXP, SEXP pageSEXP, SEXP xSEXP, SEXP ySEXP, SEXP widthSEXP, SEXP heightSEXP, SEXP contentsSEXP, SEXP rSEXP, SEXP gSEXP, SEXP bSEXP, SEXP fallback_squareSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_xptr(doc_xptrSEXP);
    Rcpp::traits::input_parameter< int >::type page(pageSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type width(widthSEXP);
    Rcpp::traits::input_parameter< double >::type height(heightSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type contents(contentsSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type fallback_square(fallback_squareSEXP);
    pdf_add_highlight_mupdf(doc_xptr, page, x, y, width, height, contents, r, g, b, fallback_square);
    return R_NilValue;
END_RCPP
}
// pdf_save_mupdf
void pdf_save_mupdf(SEXP doc_xptr, std::string outpath, bool incremental);
RcppExport SEXP _rmupdf_pdf_save_mupdf(SEXP doc_xptrSEXP, SEXP outpathSEXP, SEXP incrementalSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_xptr(doc_xptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type outpath(outpathSEXP);
    Rcpp::traits::input_parameter< bool >::type incremental(incrementalSEXP);
    pdf_save_mupdf(doc_xptr, outpath, incremental);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rmupdf_pdf_open_mupdf", (DL_FUNC) &_rmupdf_pdf_open_mupdf, 1},
    {"_rmupdf_pdf_close_mupdf", (DL_FUNC) &_rmupdf_pdf_close_mupdf, 1},
    {"_rmupdf_pdf_pages_mupdf", (DL_FUNC) &_rmupdf_pdf_pages_mupdf, 1},
    {"_rmupdf_pdf_get_metadata_mupdf", (DL_FUNC) &_rmupdf_pdf_get_metadata_mupdf, 1},
    {"_rmupdf_pdf_set_metadata_mupdf", (DL_FUNC) &_rmupdf_pdf_set_metadata_mupdf, 7},
    {"_rmupdf_pdf_list_annots_mupdf", (DL_FUNC) &_rmupdf_pdf_list_annots_mupdf, 2},
    {"_rmupdf_pdf_add_highlight_mupdf", (DL_FUNC) &_rmupdf_pdf_add_highlight_mupdf, 11},
    {"_rmupdf_pdf_save_mupdf", (DL_FUNC) &_rmupdf_pdf_save_mupdf, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmupdf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
