# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pdf_open_mupdf <- function(path) {
    .Call(`_rmupdf_pdf_open_mupdf`, path)
}

pdf_close_mupdf <- function(doc_xptr) {
    invisible(.Call(`_rmupdf_pdf_close_mupdf`, doc_xptr))
}

pdf_pages_mupdf <- function(doc_xptr) {
    .Call(`_rmupdf_pdf_pages_mupdf`, doc_xptr)
}

pdf_get_metadata_mupdf <- function(doc_xptr) {
    .Call(`_rmupdf_pdf_get_metadata_mupdf`, doc_xptr)
}

pdf_set_metadata_mupdf <- function(doc_xptr, title = NULL, author = NULL, subject = NULL, keywords = NULL, creator = NULL, producer = NULL) {
    invisible(.Call(`_rmupdf_pdf_set_metadata_mupdf`, doc_xptr, title, author, subject, keywords, creator, producer))
}

pdf_list_annots_mupdf <- function(doc_xptr, page) {
    .Call(`_rmupdf_pdf_list_annots_mupdf`, doc_xptr, page)
}

pdf_add_highlight_mupdf <- function(doc_xptr, page, x, y, width, height, contents = NULL, r = 1.0, g = 1.0, b = 0.0, fallback_square = TRUE) {
    invisible(.Call(`_rmupdf_pdf_add_highlight_mupdf`, doc_xptr, page, x, y, width, height, contents, r, g, b, fallback_square))
}

pdf_save_mupdf <- function(doc_xptr, outpath, incremental = FALSE) {
    invisible(.Call(`_rmupdf_pdf_save_mupdf`, doc_xptr, outpath, incremental))
}

